son(matvey, evgeniy).
brother(nikita, matvey).
husband(evgeniy, maria).
wife(elena, evgeniyR).
father(nikolay, evgeniy).
mother(elena, maria).
mother(maria, nikita).
mother_in_law(tatiana, maria).
father_in_law(nikolay, maria).
tesha(elena, evgeniy).
test(evgeniyR, evgeniy).
son_in_law(evgeniy, elena).
grandson(nikita, nikolay).
grandson(matvey, elena).
